check:
  - overlays-build
overlays_dir: .
overlays:
  - name: digital-twin
    build:
      base-image: "quay.io/thoth-station/s2i-elyra-custom-notebook:v0.4.1"
      build-stratergy: Dockerfile # Allowed values: Source, Dockerfile, Containerfile (default: Source)
      dockerfile-path: Dockerfile.donkey
      custom-tag: latest
      registry: quay.io
      registry-org: aicoe
      registry-project: summit-2021-octo-keynote
      registry-secret: aicoe-pusher-secret
    deploy:
      project-org: "aicoe"
      project-name: "summit-2021-octo-keynote"
      image-name: "summit-2021-octo-keynote"
      overlay-contextpath: "templates/job.yaml"

  - name: edge-device
    build:
      base-image: "quay.io/thoth-station/s2i-elyra-custom-notebook:v0.4.1"
      build-stratergy: Dockerfile # Allowed values: Source, Dockerfile, Containerfile (default: Source)
      dockerfile-path: Dockerfile.donkey.arm64
      registry: quay.io
      registry-org: aicoe
      registry-project: summit-2021-octo-keynote
      registry-secret: aicoe-pusher-secret
    deploy:
      project-org: "aicoe"
      project-name: "summit-2021-octo-keynote"
      image-name: "summit-2021-octo-keynote"
      overlay-contextpath: "templates/edge-job.yaml"
